---
name: Build ports
on:
  - push
jobs:
  test:
    uses: trombik/freebsd-ports-actions/.github/workflows/test.yml@main
    with:

      # see supported releases at:
      # https://github.com/vmactions/freebsd-vm/tree/main/conf
      freebsd_versions: "14.0"
      freebsd_ports_ref: quarterly

  portlint:
    uses: trombik/freebsd-ports-actions/.github/workflows/portlint.yml@main

  yamllint:
    uses: trombik/freebsd-ports-actions/.github/workflows/yamllint.yml@main
